site_name: LSBuilder
site_url: https://<DEIN-GITHUB-USERNAME>.github.io/<DEIN-REPO-NAME>/

docs_dir: docs

nav:
  - Start: index.md
  - Lernsituationen:
    - Ãœbersicht: lernsituationen/index.md
    - Lernfeld 1:
      - LS 1.1 Unternehmensformen: lernsituationen/LS_01_unternehmensformen/index.md
