site_name: LSBuilder
site_url: https://jtuttas.github.io/LSBuilder/

docs_dir: docs

nav:
  - Start: index.md
  - Lernsituationen:
    - Ãœbersicht: lernsituationen/index.md
    - Lernfeld 1:
      - LS 1.1 Unternehmensformen: lernsituationen/LS_01_unternehmensformen/index.md
